# version: '3.8'

# services:
#   mongodb:
#     image: mongo:latest
#     container_name: ai-learning-mongodb
#     restart: unless-stopped
#     ports:
#       - "27017:27017"
#     volumes:
#       - mongodb_data:/data/db
#     environment:
#       - MONGO_INITDB_DATABASE=ai-learning-platform

# volumes:
#   mongodb_data:
#     driver: local
services:
  mongodb:
    image: mongo:7.0
    container_name: ai-learning-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ai-learning-platform

volumes:
  mongodb_data:
    driver: local